# Generated by Django 2.1.4 on 2019-01-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190104_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='company',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
