# Generated by Django 2.1.4 on 2019-01-05 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190104_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.AddField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[('Student', 'Student'), ('Faculty', 'Faculty'), ('Community', 'Community')], default='Student', max_length=9),
        ),
    ]
