# Generated by Django 2.1.4 on 2019-01-05 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0007_auto_20190105_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('year_of_admission', models.CharField(choices=[(2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019)], max_length=4)),
                ('branch', models.CharField(choices=[('Computer', 'Computer Engineering'), ('Electrical', 'Electrical Engineering'), ('Civil', 'Civil Engineering'), ('I.T', 'I.T Engineering'), ('Mechanical', 'Mechanical Engineering')], max_length=25)),
                ('roll_number', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
