# Generated by Django 2.1.4 on 2019-01-05 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20190105_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_profile',
            name='roll_number',
        ),
    ]
