# Generated by Django 2.1.4 on 2019-01-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_student_profile_roll_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_profile',
            name='year_of_admission',
            field=models.CharField(choices=[('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019')], default='2015', max_length=5),
        ),
    ]
