# Generated by Django 2.1.4 on 2019-01-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20190105_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_profile',
            name='roll_number',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
