# Generated by Django 2.1.5 on 2019-02-02 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community_profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='faculty_profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='student_profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Community_Profile',
        ),
        migrations.DeleteModel(
            name='Faculty_Profile',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Student_Profile',
        ),
    ]
