# Generated by Django 2.1.4 on 2019-01-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190111_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='branch',
            field=models.CharField(choices=[('Computer', 'Computer Engineering'), ('Electrical', 'Electrical Engineering'), ('Civil', 'Civil Engineering'), ('I.T', 'I.T Engineering'), ('Mechanical', 'Mechanical Engineering')], default='Computer Engineering', max_length=25),
        ),
        migrations.AddField(
            model_name='post',
            name='year_of_admission',
            field=models.CharField(choices=[('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019')], default='2015', max_length=5),
        ),
    ]
