# Generated by Django 2.1.4 on 2019-01-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190112_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_admission', models.CharField(choices=[('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019')], default='2015', max_length=5)),
                ('branch', models.CharField(choices=[('Computer', 'Computer Engineering'), ('Electrical', 'Electrical Engineering'), ('Civil', 'Civil Engineering'), ('I.T', 'I.T Engineering'), ('Mechanical', 'Mechanical Engineering')], default='Computer Engineering', max_length=25)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='post',
            name='year_of_admission',
        ),
        migrations.AddField(
            model_name='post',
            name='choices',
            field=models.ManyToManyField(to='blog.Choices'),
        ),
    ]
