# Generated by Django 2.1.4 on 2019-01-12 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190112_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choices',
            name='branch',
        ),
    ]
