# Generated by Django 2.1.4 on 2019-01-13 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190112_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='branch',
        ),
    ]
