# Generated by Django 2.1.5 on 2019-01-13 14:27

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_post_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='branch',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Computer', 'Computer Engineering'), ('Electrical', 'Electrical Engineering'), ('Civil', 'Civil Engineering'), ('I.T', 'I.T Engineering'), ('Mechanical', 'Mechanical Engineering')], default='Computer Engineering', max_length=25),
        ),
    ]
