# Generated by Django 2.1.5 on 2019-01-14 12:44

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='branch',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Computer', 'Computer Engineering'), ('Electrical', 'Electrical Engineering'), ('Civil', 'Civil Engineering'), ('I.T', 'I.T Engineering'), ('Mechanical', 'Mechanical Engineering'), ('All', 'All')], default='All', max_length=25),
        ),
        migrations.AlterField(
            model_name='post',
            name='year_of_admission',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019')], default='2015', max_length=5),
        ),
    ]
