# Generated by Django 2.1.5 on 2019-01-14 17:50

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190114_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='year_of_admission',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('First Year', 'First Year'), ('Second Year', 'Second Year'), ('Third Year', 'Third Year'), ('Fourth Year', 'Fourth Year')], default='First Year', max_length=5),
        ),
    ]
