# Generated by Django 2.1.5 on 2019-01-14 18:04

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190114_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='year_of_admission',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('First', 'First Year'), ('Second', 'Second Year'), ('Third', 'Third Year'), ('Fourth', 'Fourth Year')], default='First Year', max_length=25),
        ),
    ]
