# Generated by Django 2.1.5 on 2019-02-02 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20190129_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='dislikes_comment',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='likes_comment',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='post',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='post',
            name='votes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='year_of_admission',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
